INSERT INTO `product`
values
('1','impedit','Natus fugiat aliquam mollitia amet. Et sed modi qui sint provident natus quod non. Aspernatur error autem neque labore et saepe quos.','Dolore vel unde officia earum doloremque est. Tenetur officia expedita optio provident eaque iste aut amet. Quas quisquam dolores fuga reprehenderit ab voluptatem.','32465974.68','1','nisi','http://lorempixel.com/640/480/'),
('2','intuybvd','Delectus non est dolor eos omnis maxime dolorem. Est accusantium sequi optio facere quia. Accusamus aut provident quia at consequatur non. Similique dolor dolorem magni adipisci.','Minus consequatur ut non laborum eos pariatur. Omnis architecto iste beatae dolore. Neque aut corporis molestiae at deserunt qui voluptatum omnis.','7.27','5','dolores','http://lorempixel.com/640/480/'),
('3','utbjxsb','Quia eum eaque aspernatur optio. Itaque necessitatibus nesciunt aliquam fugit. Porro sint impedit ratione nisi.','Nisi nobis corrupti et ratione unde pariatur. Voluptatem qui hic praesentium et repellendus. Ut ullam doloremque vitae quasi velit cupiditate totam blanditiis.','5167688.60','1','blanditiis','http://lorempixel.com/640/480/'),
('4','sedbjxb','Vel aut et non corrupti officiis. Illum cum sint adipisci voluptatem quia dignissimos quas. Assumenda deleniti omnis facilis veniam explicabo commodi. Itaque id vel deleniti.','Dolore delectus est quaerat laborum. Laboriosam aut aut veritatis rem harum. Neque suscipit dolores est iusto eius nostrum.','65169.67','5','culpa','http://lorempixel.com/640/480/'),
('5','deserunt','Consequatur nobis eius et incidunt voluptatem. Sapiente ea qui enim cumque hic adipisci sint assumenda. Consectetur quidem atque est repudiandae sint iure voluptatibus architecto. Cumque voluptate non vel fugiat.','Illo veritatis sunt enim adipisci vero. Aspernatur consequuntur delectus hic enim. Blanditiis molestias velit fugiat nesciunt doloremque et consequatur. Ipsa exercitationem ea unde.','0.00','1','recusandae','http://lorempixel.com/640/480/'),
('6','autnbjxb','Rerum deserunt repellendus quia perspiciatis velit. Qui non est et. Totam laudantium optio esse. Dolores qui eligendi dolorem mollitia sit corporis.','Aut ad similique qui minima reiciendis nobis. Qui repellat illum velit. Ut similique ut rerum occaecati odio.','3563766.65','6','ab','http://lorempixel.com/640/480/'),
('7','voluptatumhjx','Dicta aliquid debitis voluptates veniam id maiores quo. Qui ducimus molestias voluptatibus eos soluta et quibusdam. Quasi quibusdam et rerum vel. Enim hic ducimus consequatur sapiente ut incidunt.','Quod numquam quos eius reprehenderit quia et error autem. Ut sapiente rerum quam.','0.00','6','eum','http://lorempixel.com/640/480/'),
('8','velghdgf','Blanditiis tempore iusto saepe quasi. Placeat rerum ut voluptatem nesciunt perspiciatis dolores. Et rerum aliquam ducimus aut.','Debitis unde sit sint et rerum voluptas quo. Eaque quisquam temporibus a.','4343.75','3','quod','http://lorempixel.com/640/480/'),
('9','repellendus','Assumenda ab dolorum incidunt ipsum dicta. Velit voluptatem vel possimus quas illum est. Facilis voluptates eaque dolore minus labore.','Eos corrupti consequatur non corporis. Id alias sed assumenda corporis exercitationem. Consequatur dolores veniam ducimus aut quis minus rem.','99999999.99','9','aut','http://lorempixel.com/640/480/'),
('10','maxime','Consequuntur voluptatem sed perferendis et. Assumenda cum atque hic laborum necessitatibus incidunt. Qui incidunt laboriosam consectetur id dolor reprehenderit et.','Et tempore in ex earum neque nihil quaerat. Numquam ut qui est non ea voluptatem praesentium. Repellat tempore molestiae totam autem atque. Qui neque excepturi dolores dolores.','558.75','6','quos','http://lorempixel.com/640/480/');